/*
 * empoFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.com.empomain;

import java.awt.event.KeyEvent;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

import cn.com.dao.EmpDAO;
import cn.com.dao.impl.ImplEmpDAO;
import cn.com.entity.Empolyee;
import cn.com.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class EmpoFrame extends javax.swing.JInternalFrame {
	//创建一implempdao对象
	EmpDAO dao = new ImplEmpDAO();

	/** Creates new form empoFrame */
	public EmpoFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		empoNameLabel = new javax.swing.JLabel();
		empoDnoLabel = new javax.swing.JLabel();
		empoDescLabel = new javax.swing.JLabel();
		empoName = new javax.swing.JTextField();
		empoDno = new javax.swing.JTextField();
		empoDesc = new javax.swing.JTextArea();
		add_button = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();

		setBorder(javax.swing.BorderFactory.createBevelBorder(
				javax.swing.border.BevelBorder.RAISED, null,
				new java.awt.Color(51, 255, 153), null, null));
		setClosable(true);
		setMaximizable(true);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createBevelBorder(
						javax.swing.border.BevelBorder.RAISED,
						new java.awt.Color(0, 255, 102), new java.awt.Color(51,
								255, 51), new java.awt.Color(51, 255, 0),
						new java.awt.Color(51, 255, 0)),
				"\u5458\u5de5\u4fe1\u606f\u6dfb\u52a0",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("微软雅黑", 0, 18), new java.awt.Color(51, 51,
						255)));

		empoNameLabel.setText("\u5458\u5de5\u540d");

		empoDnoLabel.setText("\u5458\u5de5\u6240\u5728\u7684\u90e8\u95e8");

		empoDescLabel.setText("\u5458\u5de5\u63cf\u8ff0");

		empoName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				empoNameActionPerformed(evt);
			}
		});

		empoDno.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				empoDnoActionPerformed(evt);
			}
		});

		empoDesc.setColumns(20);
		empoDesc.setRows(5);
		empoDesc.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				empoDescKeyPressed(evt);
			}
		});

		add_button.setIcon(new javax.swing.ImageIcon(
				"F:\\Users\\Administrator\\mvctest\\images\\add.png")); // NOI18N
		add_button.setText("\u6dfb\u52a0");
		add_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				add_buttonActionPerformed(evt);
			}
		});

		resetButton.setIcon(new javax.swing.ImageIcon(
				"F:\\Users\\Administrator\\mvctest\\images\\reset (1).png")); // NOI18N
		resetButton.setText("\u91cd\u7f6e");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(33, 33, 33)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																empoNameLabel)
														.addComponent(
																empoDnoLabel)
														.addComponent(
																empoDescLabel))
										.addGap(63, 63, 63)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																empoDesc,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																258,
																Short.MAX_VALUE)
														.addComponent(
																empoName,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																258,
																Short.MAX_VALUE)
														.addComponent(
																empoDno,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																258,
																Short.MAX_VALUE))
										.addContainerGap())
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(52, 52, 52)
										.addComponent(add_button)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												186, Short.MAX_VALUE)
										.addComponent(resetButton)
										.addGap(58, 58, 58)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																empoNameLabel)
														.addComponent(
																empoName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(49, 49, 49)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																empoDnoLabel)
														.addComponent(
																empoDno,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(28,
																				28,
																				28)
																		.addComponent(
																				empoDesc,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(66,
																				66,
																				66)
																		.addComponent(
																				empoDescLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				67,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								add_button)
																						.addComponent(
																								resetButton))))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(25, 25, 25)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(34, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**增加用信息的empodesc属性的keyevent*/
	private void empoDescKeyPressed(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
			add();
		}

	}

	/**添加用户信息的属性dnotextField事件*/
	private void empoDnoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		add();
	}

	/**添加用户信息的textField事件*/
	private void empoNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		add();
	}

	/**重置要修改的信息*/
	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.empoName.setText("");
		this.empoDno.setText("");
		this.empoDesc.setText("");
	}

	/**增添员工信息的事件*/
	private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		add();
	}

	/**新添员工信息的方法*/
	private void add() {
		String empName = this.empoName.getText();
		String empDno = this.empoDno.getText();
		String empDesc = this.empoDesc.getText();
		if (StringUtil.isNullOrEmpty(empName)
				|| StringUtil.isNullOrEmpty(empDno)
				|| StringUtil.isNullOrEmpty(empDesc)) {
			JOptionPane.showMessageDialog(null, "员工名和员工描述和员工所在的部门号不能为空",
					"emp inf ", JOptionPane.WARNING_MESSAGE);
		}
		if (!StringUtil.isNullOrEmpty(empName)
				&& !StringUtil.isNullOrEmpty(empDno)
				&& !StringUtil.isNullOrEmpty(empDesc)) {
			Empolyee emp = new Empolyee();
			emp.setEmpName(empName);
			emp.setDno(Integer.parseInt(empDno));
			emp.setEmpDesc(empDesc);
			int count = dao.AddInfIntoOracle(emp);
			if (count == 1) {
				JOptionPane.showMessageDialog(null, "信息添加成功", "emp inf add",
						JOptionPane.INFORMATION_MESSAGE);
				this.empoName.setText("");
				this.empoDno.setText("");
				this.empoDesc.setText("");
			} else {
				JOptionPane.showMessageDialog(null, "信息添加失败", "emp inf add",
						JOptionPane.INFORMATION_MESSAGE);
			}
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton add_button;
	private javax.swing.JTextArea empoDesc;
	private javax.swing.JLabel empoDescLabel;
	private javax.swing.JTextField empoDno;
	private javax.swing.JLabel empoDnoLabel;
	private javax.swing.JTextField empoName;
	private javax.swing.JLabel empoNameLabel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton resetButton;
	// End of variables declaration//GEN-END:variables

}