/*
 * LoginOnForm.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.com.view;

import java.awt.Container;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import javax.swing.JOptionPane;

import cn.com.dao.impl.ImplUserDAO;
import cn.com.entity.User;

import cn.com.util.JdbcUtil;
import cn.com.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class LoginOnForm extends javax.swing.JFrame {

	/** Creates new form LoginOnForm */
	/*创建一个ImplUserDAO对象**/
	ImplUserDAO dao = new ImplUserDAO(JdbcUtil.getConn());

	//		@Override
	//		public void paint(Graphics g) {
	//			// TODO Auto-generated method stub
	//			super.paint(g);
	//			g.drawImage(img, 0, 0, 450, 450, this);
	//		}

	public LoginOnForm() {
		Icon img = new ImageIcon("images/bg.png");
		JLabel imgLabel = new JLabel(img);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。 
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());//设置背景标签的位置 Container cp=frame.getContentPane();
		Container c = this.getContentPane();
		((JPanel) c).setOpaque(false);
		this.setResizable(false);
		this.setIconImage(new ImageIcon("images/loginmain.png").getImage());
		initComponents();
		this.setLocation(300, 200);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		userLabel = new javax.swing.JLabel();
		userPassword = new javax.swing.JLabel();
		loginButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();
		userField = new javax.swing.JTextField();
		password = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 18));
		jLabel1.setText("\u767b\u5165\u754c\u9762\n");

		userLabel.setText("\u7528\u6237\u540d");

		userPassword.setText("\u7528\u6237\u5bc6\u7801");

		loginButton.setIcon(new javax.swing.ImageIcon(
				"F:\\Users\\Administrator\\mvctest\\images\\login.png")); // NOI18N
		loginButton.setText("\u767b\u5165");
		loginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginButtonActionPerformed(evt);
			}
		});

		resetButton.setIcon(new javax.swing.ImageIcon(
				"F:\\Users\\Administrator\\mvctest\\images\\reset (1).png")); // NOI18N
		resetButton.setText("\u91cd\u7f6e");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		userField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userFieldActionPerformed(evt);
			}
		});

		password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passwordActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(68, 68, 68)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(23, 23,
																		23)
																.addComponent(
																		loginButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		89,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		45,
																		Short.MAX_VALUE)
																.addComponent(
																		resetButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		92,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(24, 24,
																		24))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						userPassword,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						69,
																						Short.MAX_VALUE)
																				.addComponent(
																						userLabel,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						69,
																						Short.MAX_VALUE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						106,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						userField,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						186,
																						Short.MAX_VALUE)
																				.addComponent(
																						password,
																						javax.swing.GroupLayout.Alignment.TRAILING))))
								.addGap(64, 64, 64)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(15, 15, 15)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														userField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(userLabel))
								.addGap(53, 53, 53)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(userPassword)
												.addComponent(
														password,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														23,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										46, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(resetButton)
												.addComponent(loginButton))
								.addGap(56, 56, 56)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**增加一个textField事件*/
	private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		login();
	}

	/**增加一个password动作事件*/
	private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		login();
	}

	/**登入点击事件*/
	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.login();
	}

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		/*清空密码和用户名**/
		userField.setText("");
		password.setText("");
	}
	/**判断是否登入*/
	private void login(){
		/*获得用户名和密码**/
		String userName = userField.getText().trim();
		String userPassword = password.getText().trim();
		System.out.println(userPassword);
		if (StringUtil.isNullOrEmpty(userName)
				&& StringUtil.isNullOrEmpty(userPassword)) {
			JOptionPane.showMessageDialog(null, "请输入用户名和密码后再登入");
		}
		if (StringUtil.isNullOrEmpty(userName)
				&& !StringUtil.isNullOrEmpty(userPassword)) {
			JOptionPane.showMessageDialog(null, "请输入用户名后再登入");

		}
		if (StringUtil.isNullOrEmpty(userPassword)
				&& !StringUtil.isNullOrEmpty(userName)) {
			JOptionPane.showMessageDialog(null, "请输入密码后再登入");
		}
		if (!StringUtil.isNullOrEmpty(userName)
				&& !StringUtil.isNullOrEmpty(userPassword)) {
			User loginUser = new User(userName, userPassword);
			User user = dao.getUserByUP(loginUser);
			if (user == null) {
				JOptionPane.showMessageDialog(null, "登入失败", "login",
						JOptionPane.ERROR_MESSAGE);

			} else {

				JOptionPane.showMessageDialog(null, "登入成功");
				/*关闭对话框**/
				this.dispose();
				new MainFrame().setVisible(true);
			}
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginOnForm().setVisible(true);
				System.out.println(new LoginOnForm().getSize().getHeight() + ""
						+ new LoginOnForm().getSize().getWidth());
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton loginButton;
	private javax.swing.JPasswordField password;
	private javax.swing.JButton resetButton;
	private javax.swing.JTextField userField;
	private javax.swing.JLabel userLabel;
	private javax.swing.JLabel userPassword;
	// End of variables declaration//GEN-END:variables

}