/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.com.view;

import java.awt.Container;
import java.awt.JobAttributes;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

import cn.com.deptmain.DeptFrame;
import cn.com.deptmain.DeptManagerFrame;
import cn.com.empomain.EmpoFrame;
import cn.com.empomain.EmpoManagerFrame;

/**
 *
 * @author  __USER__
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		Icon img = new ImageIcon("images/zhumain.jpg");
		JLabel imgLabel = new JLabel(img);
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));//注意这里是关键，将背景标签添加到jfram的LayeredPane面板里。 
		imgLabel.setBounds(0, 0,
				img.getIconWidth(),
				img.getIconHeight());//设置背景标签的位置 Container cp=frame.getContentPane();
		Container c = this.getContentPane();
		((JPanel) c).setOpaque(false);
		//给主界面添加图标
		this.setIconImage(new ImageIcon("images/main.png").getImage());
		//主界面最大化
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		dept_Meau = new javax.swing.JMenu();
		deptAddItem = new javax.swing.JMenuItem();
		buttonselectItem = new javax.swing.JMenuItem();
		empoMeau = new javax.swing.JMenu();
		empoAddItem = new javax.swing.JMenuItem();
		empoCheckItem = new javax.swing.JMenuItem();
		exitMeau = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu1.setText("\u57fa\u7840\u6570\u636e\u7ef4\u62a4");
		

		dept_Meau.setText("\u90e8\u95e8\u7ef4\u62a4");
		

		deptAddItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_A,
				java.awt.event.InputEvent.SHIFT_MASK));
		deptAddItem.setText("\u90e8\u95e8\u6dfb\u52a0");
		deptAddItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deptAddItemActionPerformed(evt);
			}
		});
		dept_Meau.add(deptAddItem);

		buttonselectItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_C,
				java.awt.event.InputEvent.SHIFT_MASK));
		buttonselectItem.setText("\u90e8\u95e8\u67e5\u770b");
		buttonselectItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonselectItemActionPerformed(evt);
			}
		});
		dept_Meau.add(buttonselectItem);

		jMenu1.add(dept_Meau);

		empoMeau.setText("\u5458\u5de5\u7ef4\u62a4");

		empoAddItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_A,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		empoAddItem.setText("\u5458\u5de5\u6dfb\u52a0");
		empoAddItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				empoAddItemActionPerformed(evt);
			}
		});
		empoMeau.add(empoAddItem);

		empoCheckItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_C,
				java.awt.event.InputEvent.SHIFT_MASK
						| java.awt.event.InputEvent.CTRL_MASK));
		empoCheckItem.setText("\u5458\u5de5\u67e5\u770b");
		empoCheckItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				empoCheckItemActionPerformed(evt);
			}
		});
		empoMeau.add(empoCheckItem);

		jMenu1.add(empoMeau);

		exitMeau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_D,
				java.awt.event.InputEvent.CTRL_MASK));
		exitMeau.setText("\u9000\u51fa\u7cfb\u7edf");
		exitMeau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMeauActionPerformed(evt);
			}
		});
		jMenu1.add(exitMeau);

		jMenuBar1.add(jMenu1);

		jMenu3.setText("\u5173\u4e8e\u6211\u4eec");
		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**打开员工管理界面*/
	private void empoCheckItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		EmpoManagerFrame emf = new EmpoManagerFrame();
		emf.setLocation(250, 30);
		emf.setVisible(true);
		this.table.add(emf);
	}

	/**打开员工添加界面的事件*/
	private void empoAddItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		EmpoFrame emp = new EmpoFrame();
		emp.setLocation(400, 150);
		emp.setVisible(true);
		this.table.add(emp);
	}

	/**打开部门添加界面事件*/
	protected void deptAddItemActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		//创建一个部门添加界面的对象
		DeptFrame dept = new DeptFrame();
		//可视化该界面
		dept.setLocation(500,200 );
		dept.setVisible(true);
		//将该接面加入deskTop中
		this.table.add(dept);
	}

	/**打开部门管理界面的事件*/
	protected void buttonselectItemActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		//创建一个部门信息管理界面对象
		DeptManagerFrame dmf = new DeptManagerFrame();
		//可视化该界面
		dmf.setLocation(120, 10);
		dmf.setVisible(true);
		//将该界面加入deskTop中
		this.table.add(dmf);

	}

	/**关闭主界面的事件*/
	private void exitMeauActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//产生一个请求用户确认的对话框
		int selectNum = JOptionPane.showConfirmDialog(null, "是否关闭该窗体",
				"close Frame?", JOptionPane.YES_NO_CANCEL_OPTION);

		if (selectNum == JOptionPane.YES_OPTION) {
			//关闭该主界面
			this.dispose();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
				System.out.println(new MainFrame().getSize().getHeight() + "\t"
						+ new MainFrame().getSize().getWidth());
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem buttonselectItem;
	private javax.swing.JMenuItem deptAddItem;
	private javax.swing.JMenu dept_Meau;
	private javax.swing.JMenuItem empoAddItem;
	private javax.swing.JMenuItem empoCheckItem;
	private javax.swing.JMenu empoMeau;
	private javax.swing.JMenuItem exitMeau;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JDesktopPane table;
	// End of variables declaration//GEN-END:variables

}