/*
 * DeptFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.com.deptmain;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;

import javax.swing.JOptionPane;

import cn.com.dao.DeptDAO;
import cn.com.dao.impl.ImplDeptDAO;
import cn.com.entity.Dept;
import cn.com.util.JdbcUtil;
import cn.com.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class DeptFrame extends javax.swing.JInternalFrame {

	/** Creates new form DeptFrame */
	private DeptDAO dao = new ImplDeptDAO(JdbcUtil.getConn());

	public DeptFrame() {

		initComponents();
		try {
			this.setIcon(true);

		} catch (PropertyVetoException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		DeptNameLable = new javax.swing.JLabel();
		deptDescLable = new javax.swing.JLabel();
		addButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();
		deptName = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		deptDesc = new javax.swing.JTextArea();

		setClosable(true);
		setMaximizable(true);
		setTitle("\u90e8\u95e8\u6dfb\u52a0");

		DeptNameLable.setText("\u90e8\u95e8\u540d\u79f0");

		deptDescLable.setText("\u90e8\u95e8\u63cf\u8ff0");

		addButton.setIcon(new javax.swing.ImageIcon(
				"F:\\Users\\Administrator\\mvctest\\images\\add.png")); // NOI18N
		addButton.setText("\u6dfb\u52a0");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		resetButton.setIcon(new javax.swing.ImageIcon(
				"F:\\Users\\Administrator\\mvctest\\images\\reset (1).png")); // NOI18N
		resetButton.setText("\u91cd\u7f6e");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		deptName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deptNameActionPerformed(evt);
			}
		});

		deptDesc.setColumns(20);
		deptDesc.setRows(5);
		deptDesc.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				deptDescKeyPressed(evt);
			}
		});
		jScrollPane1.setViewportView(deptDesc);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		addButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		135,
																		Short.MAX_VALUE)
																.addComponent(
																		resetButton)
																.addGap(67, 67,
																		67))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						DeptNameLable)
																				.addComponent(
																						deptDescLable))
																.addGap(76, 76,
																		76)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						deptName,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						208,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						208,
																						Short.MAX_VALUE))
																.addGap(24, 24,
																		24)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(DeptNameLable)
												.addComponent(
														deptName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(34, 34,
																		34)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		deptDescLable)
																.addGap(41, 41,
																		41)))
								.addGap(24, 24, 24)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(addButton)
												.addComponent(resetButton))
								.addGap(10, 10, 10)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**textArea鍵盤事件*/
	private void deptDescKeyPressed(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if(KeyEvent.VK_ENTER==evt.getKeyCode()){
			add();
		}
		
	}

	/**textField動作事件*/
	private void deptNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		add();
	}

	/**增加清空文本内容的事件*/
	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.deptName.setText(" ");
		this.deptDesc.setText(" ");
	}

	/*增添部门信息的事件*/
	protected void addButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		add();
	}

	//增添部门信息
	private void add() {
		//new一个部门对象
		Dept dept = new Dept();
		String deptName = this.deptName.getText();
		String deptDesc = this.deptDesc.getText();
		if (StringUtil.isNullOrEmpty(deptName)
				&& !StringUtil.isNullOrEmpty(deptDesc)) {
			JOptionPane.showMessageDialog(null, "请输入要添加的部门名");
		}
		if (StringUtil.isNullOrEmpty(deptDesc)
				&& !StringUtil.isNullOrEmpty(deptName)) {
			JOptionPane.showMessageDialog(null, "请输入要添加的部门描述");
		}
		if (StringUtil.isNullOrEmpty(deptName)
				&& StringUtil.isNullOrEmpty(deptDesc)) {
			JOptionPane.showMessageDialog(null, "请输入要添加的部门名和描述");
		}

		if (!StringUtil.isNullOrEmpty(deptName)
				&& !StringUtil.isNullOrEmpty(deptDesc)) {
			dept.setDeptName(deptName);
			dept.setDeptDesc(deptDesc);
			int count = dao.AddDeptInfIntoOracle(dept);
			if (count == 1) {
				JOptionPane.showMessageDialog(null, "部门信息添加成功");
				this.deptName.setText(null);
				this.deptDesc.setText(null);
			} else {
				JOptionPane.showMessageDialog(null, "部门信息添加失败");
			}
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel DeptNameLable;
	private javax.swing.JButton addButton;
	private javax.swing.JTextArea deptDesc;
	private javax.swing.JLabel deptDescLable;
	private javax.swing.JTextField deptName;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton resetButton;
	// End of variables declaration//GEN-END:variables

}